# Generated by Django 3.2.5 on 2021-07-21 12:24

from django.db import migrations


def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).create(name='Blogger')


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="Blogger").delete()


class Migration(migrations.Migration):

    dependencies = [('blog', '0001_initial')]
    operations = [migrations.RunPython(apply_migration, revert_migration)]
