# Generated by Django 3.2.5 on 2021-07-23 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210723_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 12, 47, 13, 982690, tzinfo=utc)),
        ),
    ]
